name: ted

channels:
    - conda-forge

dependencies:
    - python=3.11
    - geopandas
    - pyyaml
    - pyarrow
    - pandas<2.1.0
    - r5py>=0.1.1.dev0
    - pip
    - pip:
        - git+https://github.com/wklumpen/gtfs-lite.git@166918312df376defae9f2a2baf213e0c7ae005e
        - python-slugify
        - pygris