name: ted

channels:
    - conda-forge

dependencies:
    - python=3.11
    - geopandas
    - pyyaml
    - pyarrow
    - pandas<2.1.0
    - r5py>=0.1.1.dev0
    - pip
    - pip:
        - git+https://github.com/wklumpen/gtfs-lite.git@5c30db06469edca6cb6f106fe718d39fd6c44d8b
        - python-slugify
        - pygris