name: ted

channels:
    - conda-forge

dependencies:
    - python=3.11
    - geopandas
    - pyyaml
    - geopandas
    - pyarrow
    - pandas<2.1.0
    - r5py>=0.1.1.dev0
    - pip
    - pip:
        - gtfs-lite
        - python-slugify