name: ted

channels:
    - conda-forge

dependencies:
    - python=3.10
    - geopandas
    - pyyaml
    - fiona
    - folium
    - geopandas
    - importlib_resources
    - matplotlib
    - mapclassify
    - numpy
    - pandas<2.1.0
    - shapely
    - pip
    - pip:
      - r5py